import {
  AlertTriangle,
  Banknote,
  Bus,
  Car,
  Circle,
  Coffee,
  CreditCard,
  Dumbbell,
  Fuel,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartPulse,
  Home,
  Landmark,
  type LucideIcon,
  PieChart,
  PiggyBank,
  Plane,
  Popcorn,
  Percent,
  Receipt,
  Repeat,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Briefcase,
  Utensils,
  Wallet,
  Zap,
} from "lucide-react";

export const ICON_OPTIONS: { name: string; icon: LucideIcon }[] = [
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Utensils", icon: Utensils },
  { name: "Coffee", icon: Coffee },
  { name: "Popcorn", icon: Popcorn },
  { name: "Car", icon: Car },
  { name: "Bus", icon: Bus },
  { name: "Fuel", icon: Fuel },
  { name: "Home", icon: Home },
  { name: "Zap", icon: Zap },
  { name: "Smartphone", icon: Smartphone },
  { name: "HeartPulse", icon: HeartPulse },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "Plane", icon: Plane },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "Gift", icon: Gift },
  { name: "HandCoins", icon: HandCoins },
  { name: "CreditCard", icon: CreditCard },
  { name: "Receipt", icon: Receipt },
  { name: "Wallet", icon: Wallet },
  { name: "PiggyBank", icon: PiggyBank },
  { name: "Banknote", icon: Banknote },
  { name: "Landmark", icon: Landmark },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "Briefcase", icon: Briefcase },
  { name: "Sparkles", icon: Sparkles },
  { name: "PieChart", icon: PieChart },
  { name: "Globe", icon: Globe },
  { name: "AlertTriangle", icon: AlertTriangle },
  { name: "Handshake", icon: Handshake },
  { name: "Repeat", icon: Repeat },
  { name: "ShieldCheck", icon: ShieldCheck },
  { name: "Tag", icon: Tag },
  { name: "Percent", icon: Percent },
  { name: "Circle", icon: Circle },
];

const ICON_MAP = new Map(ICON_OPTIONS.map((opt) => [opt.name, opt.icon]));

export function getCategoryIcon(name: string | null | undefined): LucideIcon {
  return (name && ICON_MAP.get(name)) || Circle;
}
